"use client";

import { useRouter } from "next/navigation";
import { useEffect, useRef, useState, useTransition } from "react";
import { ArrowRight, KeyRound } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/feedback";
import { Field, Input } from "@/components/ui/field";
import { Alert } from "@/components/ui/surface";
import { CopyButton } from "@/components/ui/copy-button";
import { createClient } from "@/lib/supabase/browser";

/** Six-digit one-time code input (numeric keyboard on mobile, autofill from authenticator). */
function CodeInput({ value, onChange }: { value: string; onChange: (v: string) => void }) {
  return (
    <Input
      value={value}
      onChange={(e) => onChange(e.target.value.replace(/\D/g, "").slice(0, 6))}
      inputMode="numeric"
      autoComplete="one-time-code"
      pattern="[0-9]{6}"
      maxLength={6}
      placeholder="123456"
      required
      autoFocus
      className="h-12 text-center font-mono text-[1.375rem] tracking-[0.5em]"
    />
  );
}

function errorText(message?: string) {
  if (!message) return "La vérification a échoué. Réessayez.";
  if (/invalid|expired|code/i.test(message)) return "Code incorrect ou expiré. Saisissez le code actuellement affiché dans votre application.";
  if (/rate|too many/i.test(message)) return "Trop de tentatives. Patientez une minute avant de réessayer.";
  return "La vérification a échoué. Réessayez.";
}

/** First-time setup: QR code → code → session upgraded to aal2. */
export function MfaEnrollForm({ suite }: { suite: string }) {
  const router = useRouter();
  const [factor, setFactor] = useState<{ id: string; qr: string; secret: string } | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();
  const started = useRef(false);

  useEffect(() => {
    if (started.current) return;
    started.current = true;
    (async () => {
      const supabase = createClient();
      // Remove unfinished enrollments (e.g. page reloaded before confirming).
      const { data: factors } = await supabase.auth.mfa.listFactors();
      for (const f of factors?.all ?? []) {
        if (f.factor_type === "totp" && f.status !== "verified") await supabase.auth.mfa.unenroll({ factorId: f.id });
      }
      const { data, error: enrollError } = await supabase.auth.mfa.enroll({
        factorType: "totp",
        friendlyName: `SANADY ${new Date().toISOString().slice(0, 10)}`,
        issuer: "SANADY",
      });
      if (enrollError || !data) {
        setError("Impossible de préparer la double authentification. Rechargez la page.");
        return;
      }
      setFactor({ id: data.id, qr: data.totp.qr_code, secret: data.totp.secret });
    })();
  }, []);

  const verify = () =>
    startTransition(async () => {
      if (!factor) return;
      setError(null);
      const { error: verifyError } = await createClient().auth.mfa.challengeAndVerify({ factorId: factor.id, code });
      if (verifyError) {
        setError(errorText(verifyError.message));
        return;
      }
      router.replace(suite);
      router.refresh();
    });

  return (
    <div className="space-y-5">
      {error ? <Alert tone="danger">{error}</Alert> : null}
      <ol className="space-y-5 text-body text-ink-700">
        <li>
          <p className="font-medium text-ink-900">1. Installez une application d’authentification</p>
          <p className="mt-1 text-label text-ink-600">Google Authenticator, Microsoft Authenticator ou toute application compatible (gratuites).</p>
        </li>
        <li>
          <p className="font-medium text-ink-900">2. Scannez ce code QR avec l’application</p>
          <div className="mt-3 flex flex-col items-center gap-3 rounded-xl border border-line bg-surface p-4">
            {factor ? (
              // eslint-disable-next-line @next/next/no-img-element -- data URI generated by Supabase Auth
              <img src={factor.qr} alt="Code QR de configuration de la double authentification" className="size-48" />
            ) : (
              <Skeleton className="size-48" />
            )}
            {factor ? (
              <div className="text-center">
                <p className="text-caption text-ink-500">Impossible de scanner ? Saisissez cette clé dans l’application :</p>
                <p className="mt-1 break-all font-mono text-label tracking-wider text-ink-800">{factor.secret}</p>
                <CopyButton value={factor.secret} label="Copier la clé" variant="ghost" className="mt-1" />
              </div>
            ) : null}
          </div>
        </li>
        <li>
          <p className="font-medium text-ink-900">3. Saisissez le code à 6 chiffres affiché</p>
        </li>
      </ol>
      <form
        onSubmit={(e) => {
          e.preventDefault();
          verify();
        }}
        className="space-y-4"
      >
        <Field label="Code de vérification">
          <CodeInput value={code} onChange={setCode} />
        </Field>
        <Button type="submit" variant="brand" size="xl" className="w-full" loading={pending} disabled={!factor || code.length !== 6}>
          Activer la double authentification <ArrowRight aria-hidden />
        </Button>
      </form>
    </div>
  );
}

/** At each sign-in: enter the current code → session upgraded to aal2. */
export function MfaVerifyForm({ suite }: { suite: string }) {
  const router = useRouter();
  const [factorId, setFactorId] = useState<string | null>(null);
  const [code, setCode] = useState("");
  const [error, setError] = useState<string | null>(null);
  const [pending, startTransition] = useTransition();

  useEffect(() => {
    (async () => {
      const { data } = await createClient().auth.mfa.listFactors();
      const verified = (data?.totp ?? []).find((f: { id: string; status: string }) => f.status === "verified");
      if (verified) setFactorId(verified.id);
      else router.replace(`/securite/activer?suite=${encodeURIComponent(suite)}`);
    })();
  }, [router, suite]);

  const verify = () =>
    startTransition(async () => {
      if (!factorId) return;
      setError(null);
      const { error: verifyError } = await createClient().auth.mfa.challengeAndVerify({ factorId, code });
      if (verifyError) {
        setError(errorText(verifyError.message));
        setCode("");
        return;
      }
      router.replace(suite);
      router.refresh();
    });

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        verify();
      }}
      className="space-y-4"
    >
      {error ? <Alert tone="danger">{error}</Alert> : null}
      <Field label="Code à 6 chiffres" hint="Ouvrez votre application d’authentification et saisissez le code SANADY affiché.">
        <CodeInput value={code} onChange={setCode} />
      </Field>
      <Button type="submit" variant="brand" size="xl" className="w-full" loading={pending} disabled={!factorId || code.length !== 6}>
        Vérifier <ArrowRight aria-hidden />
      </Button>
      <p className="flex items-start gap-2 text-label text-ink-500">
        <KeyRound className="mt-0.5 size-4 shrink-0" aria-hidden />
        Téléphone perdu ? Demandez à un autre administrateur SANADY de réinitialiser votre double authentification.
      </p>
    </form>
  );
}
